begin;
set local role service_role;
do $$ declare requested jsonb; claim jsonb; context jsonb; alert_nonce text; subscriber bigint; subscriber_nonce text; used_before integer; begin
 update nova_private.budget_usage set used=0,daily_used=0,usage_day=(now() at time zone 'UTC')::date where provider='resend';
 select subscriber_id,consent_nonce::text into subscriber,alert_nonce from nova_private.alerts where id=21;
 requested:=public.nova_email_consent('request','{"id":21,"version":"2026-10-01"}');
 if requested->>'status'<>'pending' then raise exception 'New consent not queued';end if;
 if public.nova_claim_digest(21,repeat('e',64))->>'skipped'<>'unconfirmed' then raise exception 'Subscriber-level consent bypass';end if;
 select consent_nonce::text into alert_nonce from nova_private.alerts where id=21;
 claim:=public.nova_email_consent('claim',jsonb_build_object('id',21,'key',repeat('f',64)));
 if claim->>'email' is null or claim->>'nonce'<>alert_nonce then raise exception 'Confirmation reservation failed';end if;
 if public.nova_email_consent('claim',jsonb_build_object('id',21,'key',repeat('f',64)))->>'skipped'<>'unavailable' then raise exception 'Repeated confirmation';end if;
 perform public.nova_email_consent('preview',jsonb_build_object('id',21,'nonce',alert_nonce));
 if (select consent_confirmed_at from nova_private.alerts where id=21) is not null then raise exception 'Preview confirms consent';end if;
 perform public.nova_email_consent('confirm',jsonb_build_object('id',21,'nonce',alert_nonce));
 context:=public.nova_email_consent('context','{"id":21}');subscriber_nonce:=context->>'nonce';
 if context->>'id' is null then raise exception 'Confirmed context unavailable';end if;
 if public.nova_claim_digest(21,repeat('e',64))->>'key' is null then raise exception 'Confirmed digest blocked';end if;
 -- A second alert to the same known address still requires independent consent.
 insert into nova_private.alerts(id,subscriber_id,query) values(50001,subscriber,'unconfirmed second query');
 if public.nova_claim_digest(50001,repeat('1',64))->>'skipped'<>'unconfirmed' then raise exception 'New alert silently confirmed';end if;
 perform public.nova_email_consent('request','{"id":50001,"version":"2026-10-01"}');
 if (select consent_requested_at from nova_private.alerts where id=50001) is not null then raise exception 'Per-address cooldown bypass';end if;
 begin perform public.nova_email_consent('preferences',jsonb_build_object('id',subscriber,'nonce','00000000-0000-0000-0000-000000000000'));raise exception 'Expected nonce denial';
 exception when raise_exception then if SQLERRM<>'Invalid subscription link' then raise;end if;end;
 update nova_private.alerts set consent_requested_at=now()-interval '73 hours' where id=50001;
 select consent_nonce::text into alert_nonce from nova_private.alerts where id=50001;
 begin perform public.nova_email_consent('confirm',jsonb_build_object('id',50001,'nonce',alert_nonce));raise exception 'Expected expiration denial';
 exception when raise_exception then if SQLERRM<>'Invalid confirmation' then raise;end if;end;
 update nova_private.alerts set consent_requested_at=now() where id=50001;
 update nova_private.budget_usage set daily_used=90 where provider='resend';
 if public.nova_email_consent('claim',jsonb_build_object('id',50001,'key',repeat('2',64)))->>'skipped'<>'quota' then raise exception 'Confirmation daily cap bypass';end if;
 update nova_private.budget_usage set daily_used=0,used=2700 where provider='resend';
 if public.nova_email_consent('claim',jsonb_build_object('id',50001,'key',repeat('2',64)))->>'skipped'<>'quota' then raise exception 'Confirmation monthly cap bypass';end if;
 perform public.nova_email_consent('unsubscribe',jsonb_build_object('id',subscriber,'nonce',subscriber_nonce));
 perform public.nova_email_consent('unsubscribe',jsonb_build_object('id',subscriber,'nonce',subscriber_nonce));
 if exists(select 1 from nova_private.alerts where subscriber_id=subscriber and enabled) then raise exception 'Unsubscribe left enabled alert';end if;
 if public.nova_email_consent('context','{"id":21}') is not null then raise exception 'Withdrawn digest context';end if;
 begin perform public.nova_email_consent('confirm',jsonb_build_object('id',50001,'nonce',alert_nonce));raise exception 'Expected revoked nonce';
 exception when raise_exception then if SQLERRM<>'Invalid confirmation' then raise;end if;end;
 begin perform public.nova_email_consent('update',jsonb_build_object('id',subscriber,'nonce',subscriber_nonce,'alert_id',21,'enabled',true,'frequency','weekly'));raise exception 'Expected withdrawn denial';
 exception when raise_exception then if SQLERRM<>'Alert unavailable' then raise;end if;end;
 if has_function_privilege('anon','public.nova_email_consent(text,jsonb)','EXECUTE') or has_function_privilege('authenticated','public.nova_email_consent(text,jsonb)','EXECUTE') then raise exception 'Private subscription RPC exposed';end if;
end $$;
rollback;
