import {handleSubscriptions,prepareConsent} from './src/services/subscription-api.js';
import {privacyConfig} from './src/services/subscriptions.js';
import {highlights} from './public/search/highlights.js';
import {gapTopics} from './public/search/engine.js';
import {SYNONYMS} from './public/search/synonyms.js';
import './src/env.js';import {authConfig} from './src/services/auth-config.js';import {uniqueOffers} from './public/search/identity.js';import crypto from 'node:crypto';import {maxAgeDays} from './src/services/liveness.js';import {createRequestBudget} from './src/services/api-limits.js';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {db,migrate,save,flushSave,storageStatus,id,refreshStorage,persistAlertRow,configureValidation,submitReport} from './src/db.js';import {seedDatabase,applyCatalogCorrections} from './src/seed.js';import {searchOffers,searchSuggestions,domainOffers,isPublishedOffer} from './src/services/search.js';import {sendDueDigests,emailStatus} from './src/services/email.js';import {startWorker,getWorkerStatus,runDiscoveryAndScan} from './src/worker.js';import {CATEGORIES} from './src/data/seed.js';import {chatWithNova,aiStatus} from './src/services/groq.js';
await migrate();await configureValidation(maxAgeDays());if(!db.offers.length)seedDatabase();else applyCatalogCorrections();await flushSave();const __dirname=path.dirname(fileURLToPath(import.meta.url));const pub=path.join(__dirname,'public');const port=Number(process.env.PORT||4310);const adminToken=process.env.ADMIN_TOKEN;
const gapBudget=createRequestBudget({limit:30,windowMs:3600000,maxConcurrent:1});
const chatBudget=createRequestBudget({limit:30,windowMs:600000,maxConcurrent:2});const alertBudget=createRequestBudget({limit:20,windowMs:60000,maxConcurrent:4});const reportBudget=createRequestBudget({limit:20,windowMs:60000,maxConcurrent:2});
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
function json(res,status,obj){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((resolve,reject)=>{let x='';let tooLarge=false;req.on('data',d=>{if(tooLarge)return;x+=d;if(x.length>1e6){tooLarge=true;reject(Object.assign(new Error('Payload too large'),{status:413}));req.resume()}});req.on('end',()=>{if(tooLarge)return;try{const parsed=x?JSON.parse(x):{};if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Invalid JSON object');resolve(parsed)}catch{reject(Object.assign(new Error('Invalid JSON object'),{status:400}))}});req.on('error',reject)})}
function auth(req){return !!adminToken && adminToken!=='change-me-now' && req.headers.authorization===`Bearer ${adminToken}`}
function staticFile(res,p){try{const s=fs.statSync(p);if(!s.isFile())return false;res.writeHead(200,{'Content-Type':types[path.extname(p)]||'application/octet-stream','Cache-Control':['account.html','preferences.html','privacy.html'].includes(path.basename(p))?'no-store':path.extname(p)==='.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(p).pipe(res);return true}catch{return false}}
const server=http.createServer(async(req,res)=>{try{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS'});return res.end()}const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(await handleSubscriptions(req,res,u,{json,body}))return;
if(p==='/api/auth-config'&&req.method==='GET')return json(res,200,authConfig());
if(p==='/api/health')return json(res,200,{ok:true,time:new Date().toISOString(),version:'2.7.1',revision:process.env.RENDER_GIT_COMMIT||null,storage:storageStatus()});
if(['/account.html','/preferences.html','/privacy.html'].includes(p)){res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; connect-src 'self' https://*.supabase.co; script-src 'self'; style-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");res.setHeader('Cache-Control','no-store');}
if(p.startsWith('/api/') && req.method==='GET' && !getWorkerStatus().localScanning)await refreshStorage();
if(p==='/api/stats'){const fresh=uniqueOffers(db.offers.filter(o=>isPublishedOffer(o)&&Date.now()-new Date(o.verified_at).getTime()<7*86400000)).length,events=db.events.filter(e=>Date.now()-new Date(e.created_at).getTime()<7*86400000).length;return json(res,200,{total:uniqueOffers(db.offers.filter(isPublishedOffer)).length,sources:db.sources.filter(s=>s.enabled).length,fresh,events})}
if(p==='/api/offers'&&req.method==='GET'){const q=u.searchParams.get('q')||'';const offers=searchOffers(Object.fromEntries(u.searchParams));return json(res,200,{offers,suggestions:offers.length?[]:searchSuggestions(q),gap_topics:offers.length?[]:gapTopics(q)})}
if(p==='/api/search-gap'&&req.method==='POST'){
 const x=await body(req),allowed=new Set(SYNONYMS.map(g=>g[0]));
 if(Object.keys(x).some(k=>k!=='topics')||!Array.isArray(x.topics)||x.topics.length<1||x.topics.length>4||x.topics.some(t=>!allowed.has(t)))return json(res,400,{error:'Invalid topics'});
 const admission=gapBudget();if(admission.retryAfter){res.setHeader('Retry-After',String(admission.retryAfter));return json(res,429,{error:'Search telemetry busy'})}
 try{for(const topic of new Set(x.topics)){const day=new Date().toISOString().slice(0,10);const existing=db.events.find(e=>e.type==='search_gap'&&e.title===topic&&e.details?.day===day);if(!existing)db.events.push({id:id('events'),type:'search_gap',title:topic,details:{day},created_at:new Date().toISOString()});}save();await flushSave();return json(res,200,{ok:true});}finally{admission.release()}
}
if(/^\/api\/offers\/\d+$/.test(p)&&req.method==='GET'){const o=db.offers.find(x=>x.id===Number(p.split('/').pop()));return isPublishedOffer(o)?json(res,200,{offer:o}):json(res,404,{error:'Not found'})}
if(p==='/api/domain-offers')return json(res,200,{offers:domainOffers(u.searchParams.get('domain'))});
if(p==='/api/meta'){return json(res,200,{categories:[...new Set(uniqueOffers(db.offers.filter(isPublishedOffer)).map(o=>o.category))].sort(),verifications:[...new Set(uniqueOffers(db.offers.filter(isPublishedOffer)).map(o=>o.verification))].sort(),categoryMeta:CATEGORIES})}
if(p==='/api/categories'){const cats=Object.entries(CATEGORIES).map(([key,v])=>({key,offers:uniqueOffers(db.offers.filter(o=>isPublishedOffer(o)&&o.category===key)).length,...v})).filter(c=>c.offers>0).sort((a,b)=>b.offers-a.offers);return json(res,200,{categories:cats})}
if(p==='/api/offers/trending'){const trending=uniqueOffers(db.offers.filter(o=>isPublishedOffer(o)&&highlights(o,{maxAge:maxAgeDays()}).length>0).sort((a,b)=>b.confidence-a.confidence)).slice(0,20);return json(res,200,{offers:trending})}
if(p==='/api/worker-status'){return json(res,200,{worker:getWorkerStatus(),db:{offers:db.offers.length,sources:db.sources.length,alerts:db.alerts.length,events:db.events.length}})}
if(p==='/api/events')return json(res,200,{events:[...db.events].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).slice(0,50)});
if(p==='/api/sources'){const q=String(u.searchParams.get('q')||'').toLowerCase().trim();let sources=[...db.sources];if(q)sources=sources.filter(x=>[x.name,x.domain,x.category,x.url].join(' ').toLowerCase().includes(q));sources.sort((a,b)=>Number(b.official)-Number(a.official)||a.name.localeCompare(b.name));return json(res,200,{sources:sources.slice(0,Math.max(1,Math.min(1000,Number(u.searchParams.get('limit'))||100)))})}
if(p==='/api/alerts'&&req.method==='POST'){const x=await body(req);if(x.consent!==undefined&&typeof x.consent!=='boolean')return json(res,400,{error:'Invalid consent'});if(x.consent===true&&!privacyConfig().ready)return json(res,503,{error:'El aviso de tratamiento está pendiente. Puedes guardar la alerta sin activar correo.'});if(typeof x.email!=='string'||x.email.length>254||!/^\S+@\S+\.\S+$/.test(x.email))return json(res,400,{error:'Valid email required'});if(!['instant','daily','weekly'].includes(x.frequency||'daily'))return json(res,400,{error:'Invalid frequency'});if(typeof x.query!=='undefined'&&(typeof x.query!=='string'||x.query.length>200))return json(res,400,{error:'Invalid query'});try{new Intl.DateTimeFormat('en',{timeZone:x.timezone||'America/Bogota'})}catch{return json(res,400,{error:'Invalid timezone'})}for(const key of ['country','category','verification','timezone'])if(x[key]!==undefined&&(typeof x[key]!=='string'||x[key].length>80))return json(res,400,{error:'Invalid alert filters'});const admission=alertBudget();if(admission.retryAfter){res.setHeader('Retry-After',String(admission.retryAfter));return json(res,429,{error:'Demasiadas alertas. Intenta más tarde.'})}try{const a={id:id('alerts'),email:x.email.toLowerCase().trim(),query:x.query||'',country:x.country||'ALL',category:x.category||'ALL',verification:x.verification||'ALL',frequency:x.frequency||'daily',timezone:x.timezone||'America/Bogota',enabled:true,last_sent_at:null,created_at:new Date().toISOString()};const existing=db.alerts.find(y=>y.enabled&&y.email===a.email&&y.query===a.query&&y.country===a.country&&y.category===a.category&&y.verification===a.verification&&y.frequency===a.frequency);if(existing){try{await flushSave()}catch{return json(res,503,{error:'No se pudo confirmar la alerta en el almacenamiento. Intenta más tarde.'})}const consent=await prepareConsent(existing,x.consent);return json(res,200,{ok:true,id:existing.id,deliveryConfigured:emailStatus().configured,...consent})}if(storageStatus().schema==='normalized'){try{const stored=await persistAlertRow(a);const consent=await prepareConsent(stored,x.consent);return json(res,200,{ok:true,id:stored.id,deliveryConfigured:emailStatus().configured,...consent})}catch{return json(res,503,{error:'No se pudo confirmar la alerta en el almacenamiento. Intenta más tarde.'})}}db.alerts.push(a);save();try{await flushSave()}catch{return json(res,503,{error:'No se pudo confirmar la alerta en el almacenamiento. Intenta más tarde.'})}return json(res,200,{ok:true,id:a.id,deliveryConfigured:false,confirmationRequired:true,confirmationQueued:false})}finally{admission.release()}}
if(p==='/api/alerts'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,{alerts:db.alerts})}
if(/^\/api\/alerts\/\d+$/.test(p)&&req.method==='DELETE'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const n=Number(p.split('/').pop());db.alerts=db.alerts.filter(x=>x.id!==n);save();try{await flushSave()}catch{return json(res,503,{error:'No se pudo confirmar el cambio en el almacenamiento.'})}return json(res,200,{ok:true})}
if(p==='/api/ai/chat'&&req.method==='POST'){const x=await body(req);if(typeof x.message!=='string'||!x.message.trim()||x.message.length>2000)return json(res,400,{error:'Escribe una pregunta de hasta 2000 caracteres.'});if(!aiStatus().enabled)return json(res,503,{error:'El asistente de IA no está configurado.'});const admission=chatBudget();if(admission.retryAfter){res.setHeader('Retry-After',String(admission.retryAfter));return json(res,429,{error:'El chat está ocupado. Intenta de nuevo en unos segundos.'})}const activeOffers=uniqueOffers(db.offers.filter(isPublishedOffer));try{const reply=await chatWithNova(x.message,activeOffers);return json(res,200,{reply,model:aiStatus().model})}catch(e){if(e.code==='AI_BUSY'){res.setHeader('Retry-After','15');return json(res,429,{error:'El chat está ocupado. Intenta de nuevo en unos segundos.'})}return json(res,503,{error:aiStatus().error==='authentication'?'La clave de Groq no es válida o no tiene acceso.':'La IA no está disponible en este momento. Intenta más tarde.',reason:aiStatus().error||'model_unavailable'})}finally{admission.release()}}
if(/^\/api\/offers\/\d+\/reports$/.test(p)&&req.method==='POST'){
 const x=await body(req);if(!['expired','changed','broken','worked'].includes(x.reason))return json(res,400,{error:'Invalid report reason'});
 const offer=db.offers.find(o=>o.id===Number(p.split('/')[3]));if(!isPublishedOffer(offer))return json(res,404,{error:'Not found'});
 const secret=process.env.REPORT_HASH_SECRET||process.env.SUPABASE_SECRET_KEY||adminToken;
 if(!secret||secret==='change-me-now')return json(res,503,{error:'Reports unavailable'});
 const reporter=crypto.createHmac('sha256',secret).update(req.socket.remoteAddress||'unknown').digest('hex');
 const admission=reportBudget();if(admission.retryAfter){res.setHeader('Retry-After',String(admission.retryAfter));return json(res,429,{error:'Reports busy'})}
 let result;try{result=await submitReport(offer.id,reporter,x.reason)}finally{admission.release()}
 if(result.limited){res.setHeader('Retry-After','86400');return json(res,429,{error:'Report limit reached'})}
 return json(res,result.unavailable?503:200,result);
}
if(p==='/api/ai/status')return json(res,200,aiStatus());
if(p==='/api/admin/scan'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'Unauthorized'});const result=await runDiscoveryAndScan({force:true});return json(res,200,{ok:true,...result})}
if(p==='/api/admin/test-digest'&&req.method==='POST'){if(!auth(req))return json(res,401,{error:'Unauthorized'});return json(res,200,{ok:true,results:await sendDueDigests({force:true})})}
if(!p.startsWith('/api/')){const rel=p==='/'?'index.html':decodeURIComponent(p.slice(1));const fp=path.resolve(pub,rel);if((fp===pub||fp.startsWith(pub+path.sep))&&staticFile(res,fp))return;if(staticFile(res,path.join(pub,'index.html')))return}
return json(res,404,{error:'Not found'});
}catch(e){console.error(e);return json(res,e.status||500,{error:e.status?e.message:'Error interno del servidor'})}});
server.listen(port,()=>{console.log(`Nova Student Radar → http://localhost:${port}`);startWorker()});
