import tls from 'node:tls';
import { db, save, flushSave } from '../db.js';
import { searchOffers } from './search.js';
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function b64(s){return Buffer.from(String(s)).toString('base64')}
async function sendResend({to,subject,html}){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM||'Nova Student <onboarding@resend.dev>',to:[to],subject,html})});if(!r.ok)throw new Error(`Resend ${r.status}: ${await r.text()}`);return r.json()}
function smtpCommand(socket,cmd,expect=[250]){return new Promise((resolve,reject)=>{let buf='';const onData=d=>{buf+=d.toString();const lines=buf.split(/\r?\n/).filter(Boolean);const last=lines.at(-1)||'';if(/^\d{3} /.test(last)){cleanup();const code=Number(last.slice(0,3));if(expect.includes(code))resolve(buf);else reject(new Error(`SMTP ${code}: ${buf.trim()}`))}};const onErr=e=>{cleanup();reject(e)};const cleanup=()=>{socket.off('data',onData);socket.off('error',onErr)};socket.on('data',onData);socket.on('error',onErr);if(cmd!==null)socket.write(cmd+'\r\n')})}
async function sendSmtp({to,subject,html}){const host=process.env.SMTP_HOST||'smtp.gmail.com',port=Number(process.env.SMTP_PORT||465),user=process.env.SMTP_USER,pass=process.env.SMTP_PASS,from=process.env.EMAIL_FROM||user;if(!user||!pass)throw new Error('Email not configured. Add RESEND_API_KEY or SMTP_USER/SMTP_PASS.');const socket=tls.connect({host,port,servername:host});await smtpCommand(socket,null,[220]);await smtpCommand(socket,'EHLO nova-student.local',[250]);await smtpCommand(socket,'AUTH LOGIN',[334]);await smtpCommand(socket,b64(user),[334]);await smtpCommand(socket,b64(pass),[235]);await smtpCommand(socket,`MAIL FROM:<${user}>`,[250]);await smtpCommand(socket,`RCPT TO:<${to}>`,[250,251]);await smtpCommand(socket,'DATA',[354]);const text=html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();const msg=[`From: ${from}`,`To: ${to}`,`Subject: =?UTF-8?B?${b64(subject)}?=`,'MIME-Version: 1.0','Content-Type: multipart/alternative; boundary="nova-boundary"','', '--nova-boundary','Content-Type: text/plain; charset=UTF-8','',text,'--nova-boundary','Content-Type: text/html; charset=UTF-8','',html,'--nova-boundary--','.'].join('\r\n').replace(/\r\n\.\r\n/g,'\r\n..\r\n');socket.write(msg+'\r\n');await smtpCommand(socket,null,[250]);await smtpCommand(socket,'QUIT',[221]);socket.end();return{ok:true}}
export async function sendMail(x){return process.env.RESEND_API_KEY?sendResend(x):sendSmtp(x)}
function localParts(date,tz){const p=new Intl.DateTimeFormat('en-CA',{timeZone:tz,weekday:'short',hour:'2-digit',hourCycle:'h23'}).formatToParts(date);return Object.fromEntries(p.map(x=>[x.type,x.value]))}
export async function sendDueDigests({force=false}={}){const results=[],now=new Date();for(const a of db.alerts.filter(x=>x.enabled)){const parts=localParts(now,a.timezone||'America/Bogota'),hour=Number(parts.hour),weekday=parts.weekday;const due=force||(a.frequency==='daily'&&hour===8)||(a.frequency==='weekly'&&weekday==='Mon'&&hour===8)||(a.frequency==='instant');if(!due)continue;const offers=searchOffers({q:a.query,country:a.country,category:a.category,verification:a.verification,limit:20});const last=a.last_sent_at?new Date(a.last_sent_at):new Date(Date.now()-7*86400000);const fresh=offers.filter(o=>new Date(o.updated_at)>last||new Date(o.discovered_at)>last);if(!force&&fresh.length===0)continue;const chosen=(force?offers:fresh).slice(0,12),rows=chosen.map(o=>`<div style="padding:16px;border:1px solid #e7e7ee;border-radius:16px;margin:12px 0"><div style="font-size:12px;color:#6b7280">${esc(o.brand)} · ${esc(o.category)}</div><h3 style="margin:5px 0">${esc(o.title)}</h3><p>${esc(o.benefit)}</p><p style="font-size:13px"><b>Requisitos:</b> ${esc((o.requirements||[]).join(' · '))}</p><a href="${esc(o.source_url)}">Ver fuente oficial</a></div>`).join('');try{await sendMail({to:a.email,subject:`🎓 Nova Student: ${chosen.length} ofertas para ti`,html:`<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto"><h1>Ofertas estudiantiles frescas</h1><p>Filtro: <b>${esc(a.query||'todas')}</b> · ${esc(a.country)} · ${esc(a.category)}</p>${rows}<p style="color:#6b7280;font-size:12px">Confirma siempre las condiciones finales en la fuente oficial antes de comprar o activar una oferta.</p></div>`});a.last_sent_at=now.toISOString();save();try{await flushSave();results.push({id:a.id,email:a.email,sent:true,count:chosen.length})}catch(e){results.push({id:a.id,email:a.email,sent:true,persisted:false,error:String(e.message||e)})}}catch(e){results.push({id:a.id,email:a.email,sent:false,error:String(e.message||e)})}}return results}
