-- Phase 1: private relational storage. No public function uses SECURITY DEFINER.
-- Keep nova_state as a protected rollback source until the owner deploys.
begin;
create schema if not exists nova_private;
revoke all on schema nova_private from public, anon, authenticated;
grant usage on schema nova_private to service_role;
-- Also supports a fresh project; never replace an existing protected snapshot.
create table if not exists public.nova_state (
  id integer primary key check(id=1), state jsonb not null,
  updated_at timestamptz not null default now()
);
alter table public.nova_state enable row level security;
revoke all on public.nova_state from public,anon,authenticated,service_role;
grant select,insert,update on public.nova_state to service_role;
create schema if not exists extensions;
create extension if not exists unaccent with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create function nova_private.touch_updated_at() returns trigger
language plpgsql set search_path = '' as $$
begin new.updated_at := clock_timestamp(); return new; end $$;
create function nova_private.search_text(value text) returns text
language sql immutable strict set search_path = '' as $$
  select lower(extensions.unaccent('extensions.unaccent'::regdictionary, value));
$$;

create table nova_private.sources (
  id bigint generated by default as identity primary key,
  name text not null, url text not null unique, domain text, category text,
  countries text[] not null default '{}', enabled boolean not null default true,
  official boolean not null default false, last_checked_at timestamptz,
  last_hash text, last_status integer, last_error text,
  extra jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.offers (
  id bigint generated by default as identity primary key,
  source_id bigint references nova_private.sources(id) on delete set null,
  slug text not null unique, brand text not null, title text not null,
  summary text, benefit text, category text, offer_type text, verification text,
  source_url text not null, source_domain text,
  countries text[] not null default '{}', requirements text[] not null default '{}',
  steps text[] not null default '{}', tags text[] not null default '{}',
  official boolean not null default false, reviewed boolean not null default false,
  status text not null default 'pending', confidence integer,
  requires_card boolean, commercial_use text,
  discovered_at timestamptz, verified_at timestamptz, expires_at timestamptz,
  source_hash text, source_excerpt text, catalog_revision text,
  liveness_score integer check (liveness_score between 0 and 100),
  liveness_status text check (liveness_status in ('active','needs_review','possibly_expired','expired','blocked')),
  consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
  extra jsonb not null default '{}',
  search_document tsvector generated always as (
    setweight(to_tsvector('pg_catalog.spanish',nova_private.search_text(coalesce(brand,'') || ' ' || coalesce(title,''))),'A') ||
    setweight(to_tsvector('pg_catalog.english',nova_private.search_text(coalesce(brand,'') || ' ' || coalesce(title,''))),'A') ||
    setweight(to_tsvector('pg_catalog.spanish',nova_private.search_text(coalesce(summary,'') || ' ' || coalesce(benefit,''))),'B') ||
    setweight(to_tsvector('pg_catalog.english',nova_private.search_text(coalesce(summary,'') || ' ' || coalesce(benefit,''))),'B')
  ) stored,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.offer_versions (
  id bigint generated always as identity primary key,
  offer_id bigint not null references nova_private.offers(id) on delete cascade,
  content_hash text not null, extraction jsonb not null,
  approved boolean not null default false, evidence text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (offer_id, content_hash)
);
create table nova_private.worker_runs (
  id bigint generated always as identity primary key,
  job_key text not null unique, window_id bigint, status text not null,
  started_at timestamptz, finished_at timestamptz, summary jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.checks (
  id bigint generated always as identity primary key,
  offer_id bigint references nova_private.offers(id) on delete cascade,
  source_id bigint references nova_private.sources(id) on delete set null,
  worker_run_id bigint references nova_private.worker_runs(id) on delete set null,
  offer_version_id bigint references nova_private.offer_versions(id) on delete set null,
  result text not null, signals jsonb not null default '{}', score integer check (score between 0 and 100),
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.events (
  id bigint generated by default as identity primary key,
  offer_id bigint references nova_private.offers(id) on delete set null,
  source_id bigint references nova_private.sources(id) on delete set null,
  type text not null, title text not null, details jsonb not null default '{}', extra jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.reports (
  id bigint generated always as identity primary key,
  offer_id bigint not null references nova_private.offers(id) on delete cascade,
  reporter_hash text not null, reason text not null, weight integer not null default 1 check (weight between 0 and 3),
  status text not null default 'pending', evidence text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.subscribers (
  id bigint generated always as identity primary key,
  email text not null unique check (length(email) <= 254 and email = lower(trim(email))),
  user_id uuid, consent_status text not null default 'unconfirmed', confirmed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.alerts (
  id bigint generated by default as identity primary key,
  subscriber_id bigint not null references nova_private.subscribers(id) on delete cascade,
  query text not null default '', country text not null default 'ALL', category text not null default 'ALL',
  verification text not null default 'ALL', frequency text not null default 'daily' check (frequency in ('instant','daily','weekly')),
  timezone text not null default 'America/Bogota', enabled boolean not null default true,
  last_sent_at timestamptz, extra jsonb not null default '{}',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.budget_usage (
  provider text not null, month text not null check (month ~ '^\d{4}-\d{2}$'),
  used integer not null default 0 check (used >= 0), lookup_used integer not null default 0 check (lookup_used >= 0),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key (provider,month)
);
-- Small runtime records per key, separate from catalog/PII and budget counters.
create table nova_private.app_runtime (
  key text primary key, value jsonb not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table nova_private.storage_control (
  id integer primary key check (id=1), mode text not null check (mode in ('legacy','normalized')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
insert into nova_private.storage_control(id,mode) values(1,'legacy');
insert into nova_private.app_runtime(key,value) values('brave','{}');

create index offers_source_id_idx on nova_private.offers(source_id);
create index offers_public_idx on nova_private.offers(verified_at desc) where status='active' and (official or reviewed);
create index offers_search_idx on nova_private.offers using gin(search_document);
create index offers_brand_trgm_idx on nova_private.offers using gin(brand extensions.gin_trgm_ops);
create index offers_countries_idx on nova_private.offers using gin(countries);
create index offers_category_idx on nova_private.offers(category);
create index sources_priority_idx on nova_private.sources(last_checked_at) where enabled;
create index versions_offer_time_idx on nova_private.offer_versions(offer_id,created_at desc);
create index checks_offer_time_idx on nova_private.checks(offer_id,checked_at desc);
create index checks_source_idx on nova_private.checks(source_id);
create index checks_worker_idx on nova_private.checks(worker_run_id);
create index checks_version_idx on nova_private.checks(offer_version_id);
create index events_offer_idx on nova_private.events(offer_id);
create index events_source_idx on nova_private.events(source_id);
create index events_time_idx on nova_private.events(created_at desc);
create index reports_offer_time_idx on nova_private.reports(offer_id,created_at desc);
create index reports_reporter_time_idx on nova_private.reports(reporter_hash,created_at desc);
create index subscribers_user_idx on nova_private.subscribers(user_id);
create index alerts_subscriber_idx on nova_private.alerts(subscriber_id);
create unique index alerts_enabled_identity_idx on nova_private.alerts(subscriber_id,query,country,category,verification,frequency) where enabled;
create index alerts_due_idx on nova_private.alerts(last_sent_at) where enabled;
create index worker_runs_started_idx on nova_private.worker_runs(started_at desc);

do $$ declare tab text; begin
  foreach tab in array array['offers','offer_versions','sources','checks','events','reports','subscribers','alerts','worker_runs','budget_usage','app_runtime','storage_control'] loop
    execute format('alter table nova_private.%I enable row level security',tab);
    execute format('revoke all on nova_private.%I from public,anon,authenticated',tab);
    execute format('grant select,insert,update,delete on nova_private.%I to service_role',tab);
    execute format('create policy backend_access on nova_private.%I for all to service_role using (true) with check (true)',tab);
    execute format('create trigger touch_updated_at before update on nova_private.%I for each row execute function nova_private.touch_updated_at()',tab);
  end loop;
end $$;
grant usage,select,update on all sequences in schema nova_private to service_role;

-- Invoker view + explicit column permission + RLS. No private schema/API exposure.
create policy published_offer_read on nova_private.offers for select to anon,authenticated
using(status='active' and (official or reviewed) and (expires_at is null or expires_at > now()));
grant select(id,slug,brand,title,summary,benefit,category,offer_type,verification,source_url,source_domain,
  countries,requirements,steps,tags,official,reviewed,status,confidence,requires_card,commercial_use,
  discovered_at,verified_at,expires_at,liveness_score,liveness_status,created_at,updated_at)
  on nova_private.offers to anon,authenticated;
create view public.public_offers with(security_invoker=true,security_barrier=true) as
select id,slug,brand,title,summary,benefit,category,offer_type,verification,source_url,source_domain,
  countries,requirements,steps,tags,official,reviewed,status,confidence,requires_card,commercial_use,
  discovered_at,verified_at,expires_at,liveness_score,liveness_status,created_at,updated_at
from nova_private.offers
where status='active' and (official or reviewed) and (expires_at is null or expires_at > now());
revoke all on public.public_offers from public,anon,authenticated;
grant select on public.public_offers to anon,authenticated,service_role;

-- Compatibility serialization never exposes extra/internal fields in public_offers.
create function nova_private.legacy_row(kind text,row_data jsonb) returns jsonb
language plpgsql stable set search_path='' as $$
declare result jsonb; k text;
begin
  result := coalesce(row_data->'extra','{}'::jsonb) || (row_data - array['extra','search_document','subscriber_id']);
  foreach k in array array['created_at','updated_at','discovered_at','verified_at','expires_at','last_checked_at','last_sent_at'] loop
    if result->>k is not null then
      result := jsonb_set(result,array[k],to_jsonb(to_char((result->>k)::timestamptz at time zone 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')));
    end if;
  end loop;
  return result;
end;
$$;

create function nova_private.write_row(kind text,input jsonb,expected jsonb default null,operation text default 'upsert')
returns jsonb language plpgsql set search_path='' as $$
declare current_row jsonb; current_legacy jsonb; patch jsonb; extra_data jsonb; columns text; values_sql text;
  assignment text; known text[]; k text; row_id bigint; subscriber bigint; typed_patch jsonb; changed boolean:=false;
begin
  if kind not in ('offers','sources','events','alerts') then raise exception 'Unsupported collection'; end if;
  if jsonb_typeof(input) <> 'object' or not(input ? 'id') then raise exception 'Invalid row'; end if;
  row_id := (input->>'id')::bigint;
  execute format('select to_jsonb(t) from nova_private.%I t where id=$1 for update',kind) into current_row using row_id;
  current_legacy := nova_private.legacy_row(kind,current_row);
  if kind='alerts' and current_row is not null then
    current_legacy := current_legacy || jsonb_build_object('email',(select email from nova_private.subscribers where id=(current_row->>'subscriber_id')::bigint));
  end if;
  if expected is not null then
    if current_row is null then raise exception using errcode='40001',message='Row removed by another writer'; end if;
    for k in select jsonb_object_keys(expected) loop
      if coalesce(current_legacy->k,'null'::jsonb) is distinct from coalesce(expected->k,'null'::jsonb) then
        raise exception using errcode='40001',message='Concurrent row edit';
      end if;
    end loop;
  elsif current_row is not null then
    -- A repeated request may safely repeat the same insertion, never replace a different row.
    if operation <> 'import' then
      for k in select jsonb_object_keys(input) loop
        if current_legacy->k is distinct from input->k then
          raise exception using errcode='40001',message='Concurrent insertion';
        end if;
      end loop;
      return current_legacy;
    end if;
  end if;
  if operation='delete' then
    execute format('delete from nova_private.%I where id=$1',kind) using row_id;
    return null;
  end if;
  patch := input - array['id','updated_at','created_at','search_document','extra'];
  if kind='offers' and input ? 'source_url' and not(input ? 'source_id') then
    patch := patch || jsonb_build_object('source_id',(select id from nova_private.sources where url=input->>'source_url'));
  end if;
  if current_row is null and input ? 'created_at' then patch := patch || jsonb_build_object('created_at',input->'created_at'); end if;
  if kind='alerts' then
    if input ? 'email' then
      insert into nova_private.subscribers(email) values(lower(trim(input->>'email')))
      on conflict(email) do update set email=excluded.email returning id into subscriber;
      patch := (patch - 'email') || jsonb_build_object('subscriber_id',subscriber);
    elsif current_row is null then raise exception 'An alert needs a subscriber'; end if;
  end if;
  select array_agg(attname::text) into known from pg_catalog.pg_attribute
  where attrelid=format('nova_private.%I',kind)::regclass and attnum>0 and not attisdropped and attgenerated='';
  extra_data := coalesce(current_row->'extra','{}'::jsonb) || (patch - known);
  patch := (patch - coalesce((select array_agg(key) from jsonb_object_keys(patch) key where not(key=any(known))),'{}'::text[])) || jsonb_build_object('extra',extra_data);
  execute format('select to_jsonb(jsonb_populate_record(null::nova_private.%I,$1))',kind) into typed_patch using patch;
  for k in select jsonb_object_keys(patch) loop
    if current_row->k is distinct from typed_patch->k then changed:=true; end if;
  end loop;
  -- No unknown JSON keys are ever interpolated into SQL identifiers.
  select string_agg(format('%I',key),','),
    string_agg(format('(jsonb_populate_record(null::nova_private.%I,$1)).%I',kind,key),','),
    string_agg(format('%I=(jsonb_populate_record(null::nova_private.%I,$1)).%I',key,kind,key),',')
  into columns,values_sql,assignment from jsonb_object_keys(patch) key;
  if current_row is null then
    execute format('insert into nova_private.%I(id,%s) select $2,%s returning to_jsonb(%I.*)',kind,columns,values_sql,kind)
    into current_row using patch,row_id;
  elsif changed then
    execute format('update nova_private.%I set %s where id=$2 returning to_jsonb(%I.*)',kind,assignment,kind)
    into current_row using patch,row_id;
  end if;
  if kind='offers' then
    input := nova_private.legacy_row(kind,current_row);
    insert into nova_private.offer_versions(offer_id,content_hash,extraction,approved,evidence)
    values(row_id,md5((input - array['verified_at','updated_at','created_at'])::text),input,
      operation='import' and (coalesce((input->>'official')::boolean,false) or coalesce((input->>'reviewed')::boolean,false)),left(input->>'source_excerpt',500))
    on conflict(offer_id,content_hash) do nothing;
  end if;
  return nova_private.legacy_row(kind,current_row);
end $$;

-- Loads table rows, not nova_state; service_role only. Consumers retain existing IDs/API.
create function public.nova_load_rows() returns jsonb
language sql stable set search_path='' as $$
  select jsonb_build_object(
    'offers',(select coalesce(jsonb_agg(nova_private.legacy_row('offers',to_jsonb(o)) order by id),'[]') from nova_private.offers o),
    'sources',(select coalesce(jsonb_agg(nova_private.legacy_row('sources',to_jsonb(s)) order by id),'[]') from nova_private.sources s),
    'events',(select coalesce(jsonb_agg(nova_private.legacy_row('events',to_jsonb(e)) order by id),'[]') from nova_private.events e),
    'alerts',(select coalesce(jsonb_agg(nova_private.legacy_row('alerts',to_jsonb(a)) || jsonb_build_object('email',s.email) order by a.id),'[]') from nova_private.alerts a join nova_private.subscribers s on s.id=a.subscriber_id),
    'favorites',coalesce((select value from nova_private.app_runtime where key='_legacy_favorites'),'[]'),
    'runtime',coalesce((select jsonb_object_agg(key,value) from nova_private.app_runtime where key not like '\_%'),'{}') ||
      jsonb_build_object('brave',coalesce((select value from nova_private.app_runtime where key='brave'),'{}') ||
        jsonb_build_object('month',to_char(now() at time zone 'UTC','YYYY-MM'),
          'used',coalesce((select used from nova_private.budget_usage where provider='brave' and month=to_char(now() at time zone 'UTC','YYYY-MM')),0),
          'lookupUsed',coalesce((select lookup_used from nova_private.budget_usage where provider='brave' and month=to_char(now() at time zone 'UTC','YYYY-MM')),0)))
  );
$$;

create function public.nova_apply_changes(changes jsonb) returns jsonb
language plpgsql set search_path='' as $$
declare c jsonb; current_value jsonb; k text; has_current boolean;
begin
  if (select mode from nova_private.storage_control where id=1) is distinct from 'normalized' then raise exception 'Normalized storage is not active'; end if;
  if jsonb_typeof(changes)<>'array' or jsonb_array_length(changes)>1000 then raise exception 'Invalid change batch'; end if;
  for c in select value from jsonb_array_elements(changes) loop
    if c->>'collection'='runtime' then
      k := c->'patch'->>'key';
      if k is null or k like '\_%' then raise exception 'Reserved runtime key'; end if;
      select value into current_value from nova_private.app_runtime where key=k for update;
      has_current := found;
      if coalesce(current_value,'null'::jsonb) is distinct from coalesce(c->'expected'->'value','null'::jsonb) then raise exception using errcode='40001',message='Concurrent runtime edit'; end if;
      if has_current then
        update nova_private.app_runtime set value=c->'patch'->'value' where key=k;
      else
        insert into nova_private.app_runtime(key,value) values(k,c->'patch'->'value') on conflict do nothing;
        if not found then raise exception using errcode='40001',message='Concurrent runtime insertion'; end if;
      end if;
    else
      perform nova_private.write_row(c->>'collection',c->'patch',nullif(c->'expected','null'::jsonb),coalesce(c->>'operation','upsert'));
    end if;
  end loop;
  return jsonb_build_object('applied',jsonb_array_length(changes));
end $$;

-- Atomic ID blocks preserve numeric IDs used by the web and extension.
create function public.nova_reserve_ids(amount integer default 1000) returns jsonb
language plpgsql set search_path='' as $$
declare kind text; seq_name text; first_id bigint; last_id bigint; result jsonb := '{}';
begin
  if amount not between 1 and 10000 then raise exception 'Invalid ID block'; end if;
  perform pg_advisory_xact_lock(71001);
  foreach kind in array array['offers','sources','events','alerts'] loop
    seq_name := pg_get_serial_sequence(format('nova_private.%I',kind),'id');
    first_id := nextval(seq_name::regclass);
    last_id := first_id + amount - 1;
    perform setval(seq_name::regclass,last_id,true);
    result := result || jsonb_build_object(kind,jsonb_build_object('next',first_id,'last',last_id));
  end loop;
  return result;
end $$;

create function public.nova_reserve_brave(month_key text,purpose text,total_limit integer) returns jsonb
language plpgsql set search_path='' as $$
declare usage nova_private.budget_usage; cap integer := least(greatest(total_limit,0),600);
begin
  if month_key <> to_char(now() at time zone 'UTC','YYYY-MM') or purpose not in ('discovery','lookup') then raise exception 'Invalid budget request'; end if;
  insert into nova_private.budget_usage(provider,month) values('brave',month_key) on conflict do nothing;
  select * into usage from nova_private.budget_usage where provider='brave' and month=month_key for update;
  if usage.used >= cap then return jsonb_build_object('skipped','monthly_limit','used',usage.used,'lookupUsed',usage.lookup_used); end if;
  if purpose='lookup' and usage.lookup_used >=100 then return jsonb_build_object('skipped','lookup_limit','used',usage.used,'lookupUsed',usage.lookup_used); end if;
  update nova_private.budget_usage set used=used+1,lookup_used=lookup_used+case when purpose='lookup' then 1 else 0 end
  where provider='brave' and month=month_key returning * into usage;
  return jsonb_build_object('used',usage.used,'lookupUsed',usage.lookup_used);
end $$;

create function public.nova_create_alert(input jsonb) returns jsonb
language plpgsql set search_path='' as $$
declare subscriber bigint; result nova_private.alerts;
begin
  if (select mode from nova_private.storage_control where id=1) is distinct from 'normalized' then raise exception 'Normalized storage is not active'; end if;
  insert into nova_private.subscribers(email) values(lower(trim(input->>'email')))
  on conflict(email) do update set email=excluded.email returning id into subscriber;
  insert into nova_private.alerts(id,subscriber_id,query,country,category,verification,frequency,timezone)
  values((input->>'id')::bigint,subscriber,coalesce(input->>'query',''),coalesce(input->>'country','ALL'),
    coalesce(input->>'category','ALL'),coalesce(input->>'verification','ALL'),coalesce(input->>'frequency','daily'),coalesce(input->>'timezone','America/Bogota'))
  on conflict(subscriber_id,query,country,category,verification,frequency) where enabled
  do update set enabled=true returning * into result;
  return nova_private.legacy_row('alerts',to_jsonb(result)) || jsonb_build_object('email',lower(trim(input->>'email')));
end $$;

revoke all on all functions in schema nova_private from public,anon,authenticated;
grant execute on all functions in schema nova_private to service_role;
revoke all on function public.nova_load_rows(), public.nova_apply_changes(jsonb),public.nova_reserve_ids(integer),public.nova_reserve_brave(text,text,integer),public.nova_create_alert(jsonb) from public,anon,authenticated;
grant execute on function public.nova_load_rows(), public.nova_apply_changes(jsonb),public.nova_reserve_ids(integer),public.nova_reserve_brave(text,text,integer),public.nova_create_alert(jsonb) to service_role;
-- Idempotent backfill. Existing IDs are imported, never invented or published anew.
create function nova_private.import_state(payload jsonb) returns void
language plpgsql set search_path='' as $$
declare r jsonb; k text; v jsonb; seq_name text; maximum bigint; seq_value bigint;
begin
  if jsonb_typeof(payload)<>'object' then raise exception 'Invalid legacy snapshot'; end if;
  perform pg_advisory_xact_lock(71001);
  for r in select value from jsonb_array_elements(coalesce(payload->'sources','[]')) loop
    perform nova_private.write_row('sources',r,null,'import');
  end loop;
  for r in select value from jsonb_array_elements(coalesce(payload->'offers','[]')) loop
    if not(r ? 'source_id') then
      r := r || jsonb_build_object('source_id',(select id from nova_private.sources where url=r->>'source_url'));
    end if;
    perform nova_private.write_row('offers',r,null,'import');
  end loop;
  for r in select value from jsonb_array_elements(coalesce(payload->'events','[]')) loop
    if r ? 'source_id' and not exists(select 1 from nova_private.sources where id=(r->>'source_id')::bigint) then
      r := (r-'source_id') || jsonb_build_object('legacy_source_id',r->'source_id');
    end if;
    if r ? 'offer_id' and not exists(select 1 from nova_private.offers where id=(r->>'offer_id')::bigint) then
      r := (r-'offer_id') || jsonb_build_object('legacy_offer_id',r->'offer_id');
    end if;
    perform nova_private.write_row('events',r,null,'import');
  end loop;
  for r in select value from jsonb_array_elements(coalesce(payload->'alerts','[]')) loop
    perform nova_private.write_row('alerts',r,null,'import');
  end loop;
  -- Match deletions performed by the legacy owner before cutover; never run in normalized mode.
  delete from nova_private.alerts where id not in (select (value->>'id')::bigint from jsonb_array_elements(coalesce(payload->'alerts','[]')));
  for k,v in select key,value from jsonb_each(coalesce(payload->'runtime','{}')) loop
    if k='brave' then
      if v ? 'month' then
        insert into nova_private.budget_usage(provider,month,used,lookup_used)
        values('brave',v->>'month',greatest(coalesce((v->>'used')::integer,0),0),greatest(coalesce((v->>'lookupUsed')::integer,0),0))
        on conflict(provider,month) do update set used=greatest(budget_usage.used,excluded.used),lookup_used=greatest(budget_usage.lookup_used,excluded.lookup_used);
      end if;
      v := v - array['month','used','lookupUsed'];
    end if;
    insert into nova_private.app_runtime(key,value) values(k,v) on conflict(key) do update set value=excluded.value where app_runtime.value is distinct from excluded.value;
  end loop;
  insert into nova_private.app_runtime(key,value) values('_legacy_favorites',coalesce(payload->'favorites','[]'))
  on conflict(key) do update set value=excluded.value where app_runtime.value is distinct from excluded.value;
  v := payload->'runtime'->'worker';
  if v ? 'lastWindow' then
    insert into nova_private.worker_runs(job_key,window_id,status,started_at,finished_at,summary)
    values('legacy:' || (v->>'lastWindow'),(v->>'lastWindow')::bigint,
      case when v->>'lastError' is not null then 'failed' when v->>'lastCompletedAt' is not null then 'completed' else 'started' end,
      (v->>'lastStartedAt')::timestamptz,(v->>'lastCompletedAt')::timestamptz,coalesce(v->'lastScanResult','{}'))
    on conflict(job_key) do update set status=excluded.status,finished_at=excluded.finished_at,summary=excluded.summary;
  end if;
  foreach k in array array['offers','sources','events','alerts'] loop
    seq_name := pg_get_serial_sequence(format('nova_private.%I',k),'id');
    execute format('select coalesce(max(id),0) from nova_private.%I',k) into maximum;
    execute format('select last_value from %s',seq_name) into seq_value;
    perform setval(seq_name::regclass,greatest(maximum,seq_value,1),true);
  end loop;
end $$;

create function public.nova_import_snapshot() returns jsonb
language plpgsql set search_path='' as $$
declare payload jsonb;
begin
  perform pg_advisory_xact_lock(71000);
  if (select mode from nova_private.storage_control where id=1) is distinct from 'legacy' then raise exception 'Import is disabled after cutover'; end if;
  select state into payload from public.nova_state where id=1;
  if payload is not null then perform nova_private.import_state(payload); end if;
  return jsonb_build_object('offers',(select count(*) from nova_private.offers),'sources',(select count(*) from nova_private.sources),
    'alerts',(select count(*) from nova_private.alerts),'events',(select count(*) from nova_private.events));
end $$;

create function nova_private.sync_legacy_snapshot() returns trigger
language plpgsql set search_path='' as $$
begin
  perform pg_advisory_xact_lock(71000);
  if (select mode from nova_private.storage_control where id=1)='normalized' then
    raise exception 'Legacy snapshot writes disabled; deploy normalized code or use documented rollback';
  end if;
  perform nova_private.import_state(new.state);
  return new;
end $$;
create trigger sync_normalized_rows after insert or update on public.nova_state
for each row execute function nova_private.sync_legacy_snapshot();

create function public.nova_activate_rows() returns jsonb
language plpgsql set search_path='' as $$
begin
  -- Lock order matches an old snapshot writer: nova_state first, then advisory lock.
  perform 1 from public.nova_state where id=1 for update;
  perform pg_advisory_xact_lock(71000);
  if (select mode from nova_private.storage_control where id=1)='legacy' then
    perform public.nova_import_snapshot();
    update nova_private.storage_control set mode='normalized' where id=1;
  end if;
  return public.nova_load_rows();
end $$;

-- Native counters remain authoritative when a different process reserved an attempt.
create function public.nova_export_rollback() returns jsonb
language plpgsql set search_path='' as $$
declare state jsonb; seq jsonb:='{}'; k text; n bigint;
begin
  state := public.nova_load_rows();
  foreach k in array array['offers','sources','events','alerts'] loop
    execute format('select coalesce(max(id),0) from nova_private.%I',k) into n;
    seq := seq || jsonb_build_object(k,n);
  end loop;
  return state || jsonb_build_object('seq',seq || jsonb_build_object('favorites',0));
end $$;

revoke all on all functions in schema nova_private from public,anon,authenticated;
grant execute on all functions in schema nova_private to service_role;
revoke all on function public.nova_import_snapshot(),public.nova_activate_rows(),public.nova_export_rollback() from public,anon,authenticated;
grant execute on function public.nova_import_snapshot(),public.nova_activate_rows(),public.nova_export_rollback() to service_role;
-- Preserve an existing empty/bootstrap table and all of its private contents.
select public.nova_import_snapshot();
notify pgrst, 'reload schema';
commit;
